
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import dotenv from "dotenv";
import path from "path";

// Load .env.local so Prisma uses the same single source as Next.js (no duplicate .env)
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });
import { defineConfig, env } from "prisma/config";

// Helper function to convert pooler URL to direct connection URL
// Prisma migrations require a direct connection (port 5432) instead of pooler (port 6543)
function getDirectConnectionUrl(url: string): string {
  // If using Supabase pooler (port 6543), convert to direct connection (port 5432)
  if (url.includes(':6543')) {
    return url.replace(':6543', ':5432');
  }
  // If already using direct connection or other provider, return as-is
  // But add ?pgbouncer=true if it's a pooler connection
  if (url.includes('pooler') && !url.includes('?pgbouncer=true')) {
    return url + (url.includes('?') ? '&' : '?') + 'pgbouncer=true';
  }
  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: getDirectConnectionUrl(env("DATABASE_URL")),
  },
});
