-- Disable Row Level Security (RLS) on all tables
-- Run this in Supabase SQL Editor if RLS is blocking queries
-- This allows queries to work with both anon key and service role key

-- Disable RLS on all main tables
ALTER TABLE IF EXISTS clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS upcoming_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS vendors DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS menu_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS box_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS box_quotas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS item_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS client_statuses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS navigators DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS nutritionists DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS app_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS form_submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS signatures DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS billing_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS delivery_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_vendor_selections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_box_selections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS upcoming_order_vendor_selections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS upcoming_order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS upcoming_order_box_selections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS stops DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS drivers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS routes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS equipment DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS forms DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS filled_forms DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS form_answers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS navigator_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS city_colors DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS passwordless_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS route_runs DISABLE ROW LEVEL SECURITY;

-- Verify RLS is disabled (optional check)
SELECT 
    schemaname,
    tablename,
    rowsecurity as rls_enabled
FROM pg_tables t
LEFT JOIN pg_class c ON c.relname = t.tablename
LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE schemaname = 'public'
AND tablename IN (
    'clients', 'orders', 'vendors', 'menu_items', 'upcoming_orders',
    'client_statuses', 'box_types', 'navigators', 'admins'
)
ORDER BY tablename;
