-- Alternative: Enable permissive RLS policies instead of disabling RLS
-- Use this if you want to keep RLS enabled but allow all operations
-- Run this in Supabase SQL Editor

-- Enable RLS on tables
ALTER TABLE IF EXISTS clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS upcoming_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS box_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS box_quotas ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS item_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS client_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS navigators ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS nutritionists ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS form_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS billing_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS delivery_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_vendor_selections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_box_selections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS upcoming_order_vendor_selections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS upcoming_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS upcoming_order_box_selections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS filled_forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS form_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS navigator_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS city_colors ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS passwordless_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS route_runs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (optional - comment out if you want to keep existing policies)
-- DROP POLICY IF EXISTS "Allow all operations" ON clients;
-- DROP POLICY IF EXISTS "Allow all operations" ON orders;
-- ... (repeat for other tables)

-- Drop existing policies if they exist (using DO block to handle errors gracefully)
DO $$
BEGIN
    DROP POLICY IF EXISTS "Allow public read" ON clients;
    DROP POLICY IF EXISTS "Allow public read" ON orders;
    DROP POLICY IF EXISTS "Allow public read" ON upcoming_orders;
    DROP POLICY IF EXISTS "Allow public read" ON vendors;
    DROP POLICY IF EXISTS "Allow public read" ON menu_items;
    DROP POLICY IF EXISTS "Allow public read" ON box_types;
    DROP POLICY IF EXISTS "Allow public read" ON box_quotas;
    DROP POLICY IF EXISTS "Allow public read" ON item_categories;
    DROP POLICY IF EXISTS "Allow public read" ON client_statuses;
    DROP POLICY IF EXISTS "Allow public read" ON navigators;
    DROP POLICY IF EXISTS "Allow public read" ON nutritionists;
    DROP POLICY IF EXISTS "Allow public read" ON admins;
    DROP POLICY IF EXISTS "Allow public read" ON app_settings;
    DROP POLICY IF EXISTS "Allow public read" ON form_submissions;
    DROP POLICY IF EXISTS "Allow public read" ON signatures;
    DROP POLICY IF EXISTS "Allow public read" ON billing_records;
    DROP POLICY IF EXISTS "Allow public read" ON delivery_history;
    DROP POLICY IF EXISTS "Allow public read" ON order_vendor_selections;
    DROP POLICY IF EXISTS "Allow public read" ON order_items;
    DROP POLICY IF EXISTS "Allow public read" ON order_box_selections;
    DROP POLICY IF EXISTS "Allow public read" ON upcoming_order_vendor_selections;
    DROP POLICY IF EXISTS "Allow public read" ON upcoming_order_items;
    DROP POLICY IF EXISTS "Allow public read" ON upcoming_order_box_selections;
    DROP POLICY IF EXISTS "Allow public read" ON stops;
    DROP POLICY IF EXISTS "Allow public read" ON drivers;
    DROP POLICY IF EXISTS "Allow public read" ON routes;
    DROP POLICY IF EXISTS "Allow public read" ON equipment;
    DROP POLICY IF EXISTS "Allow public read" ON forms;
    DROP POLICY IF EXISTS "Allow public read" ON questions;
    DROP POLICY IF EXISTS "Allow public read" ON filled_forms;
    DROP POLICY IF EXISTS "Allow public read" ON form_answers;
    DROP POLICY IF EXISTS "Allow public read" ON order_history;
    DROP POLICY IF EXISTS "Allow public read" ON navigator_logs;
    DROP POLICY IF EXISTS "Allow public read" ON schedules;
    DROP POLICY IF EXISTS "Allow public read" ON settings;
    DROP POLICY IF EXISTS "Allow public read" ON city_colors;
    DROP POLICY IF EXISTS "Allow public read" ON passwordless_codes;
    DROP POLICY IF EXISTS "Allow public read" ON route_runs;
EXCEPTION
    WHEN undefined_object THEN NULL;
END $$;

-- Create permissive policies for SELECT (read)
CREATE POLICY "Allow public read" ON clients FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON orders FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON upcoming_orders FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON vendors FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON menu_items FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON box_types FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON box_quotas FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON item_categories FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON client_statuses FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON navigators FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON nutritionists FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON admins FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON app_settings FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON form_submissions FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON signatures FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON billing_records FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON delivery_history FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON order_vendor_selections FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON order_items FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON order_box_selections FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON upcoming_order_vendor_selections FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON upcoming_order_items FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON upcoming_order_box_selections FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON stops FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON drivers FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON routes FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON equipment FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON forms FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON questions FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON filled_forms FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON form_answers FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON order_history FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON navigator_logs FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON schedules FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON settings FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON city_colors FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON passwordless_codes FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON route_runs FOR SELECT USING (true);

-- Drop existing INSERT policies
DO $$
BEGIN
    DROP POLICY IF EXISTS "Allow public insert" ON clients;
    DROP POLICY IF EXISTS "Allow public insert" ON orders;
    DROP POLICY IF EXISTS "Allow public insert" ON upcoming_orders;
    DROP POLICY IF EXISTS "Allow public insert" ON vendors;
    DROP POLICY IF EXISTS "Allow public insert" ON menu_items;
    DROP POLICY IF EXISTS "Allow public insert" ON box_types;
    DROP POLICY IF EXISTS "Allow public insert" ON box_quotas;
    DROP POLICY IF EXISTS "Allow public insert" ON item_categories;
    DROP POLICY IF EXISTS "Allow public insert" ON client_statuses;
    DROP POLICY IF EXISTS "Allow public insert" ON navigators;
    DROP POLICY IF EXISTS "Allow public insert" ON nutritionists;
    DROP POLICY IF EXISTS "Allow public insert" ON admins;
    DROP POLICY IF EXISTS "Allow public insert" ON app_settings;
    DROP POLICY IF EXISTS "Allow public insert" ON form_submissions;
    DROP POLICY IF EXISTS "Allow public insert" ON signatures;
    DROP POLICY IF EXISTS "Allow public insert" ON billing_records;
    DROP POLICY IF EXISTS "Allow public insert" ON delivery_history;
    DROP POLICY IF EXISTS "Allow public insert" ON order_vendor_selections;
    DROP POLICY IF EXISTS "Allow public insert" ON order_items;
    DROP POLICY IF EXISTS "Allow public insert" ON order_box_selections;
    DROP POLICY IF EXISTS "Allow public insert" ON upcoming_order_vendor_selections;
    DROP POLICY IF EXISTS "Allow public insert" ON upcoming_order_items;
    DROP POLICY IF EXISTS "Allow public insert" ON upcoming_order_box_selections;
    DROP POLICY IF EXISTS "Allow public insert" ON stops;
    DROP POLICY IF EXISTS "Allow public insert" ON drivers;
    DROP POLICY IF EXISTS "Allow public insert" ON routes;
    DROP POLICY IF EXISTS "Allow public insert" ON equipment;
    DROP POLICY IF EXISTS "Allow public insert" ON forms;
    DROP POLICY IF EXISTS "Allow public insert" ON questions;
    DROP POLICY IF EXISTS "Allow public insert" ON filled_forms;
    DROP POLICY IF EXISTS "Allow public insert" ON form_answers;
    DROP POLICY IF EXISTS "Allow public insert" ON order_history;
    DROP POLICY IF EXISTS "Allow public insert" ON navigator_logs;
    DROP POLICY IF EXISTS "Allow public insert" ON schedules;
    DROP POLICY IF EXISTS "Allow public insert" ON settings;
    DROP POLICY IF EXISTS "Allow public insert" ON city_colors;
    DROP POLICY IF EXISTS "Allow public insert" ON passwordless_codes;
    DROP POLICY IF EXISTS "Allow public insert" ON route_runs;
EXCEPTION
    WHEN undefined_object THEN NULL;
END $$;

-- Create permissive policies for INSERT
CREATE POLICY "Allow public insert" ON clients FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON upcoming_orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON vendors FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON menu_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON box_types FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON box_quotas FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON item_categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON client_statuses FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON navigators FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON nutritionists FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON admins FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON app_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON form_submissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON signatures FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON billing_records FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON delivery_history FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON order_vendor_selections FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON order_box_selections FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON upcoming_order_vendor_selections FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON upcoming_order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON upcoming_order_box_selections FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON stops FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON drivers FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON routes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON equipment FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON forms FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON questions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON filled_forms FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON form_answers FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON order_history FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON navigator_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON schedules FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON city_colors FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON passwordless_codes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert" ON route_runs FOR INSERT WITH CHECK (true);

-- Drop existing UPDATE policies
DO $$
BEGIN
    DROP POLICY IF EXISTS "Allow public update" ON clients;
    DROP POLICY IF EXISTS "Allow public update" ON orders;
    DROP POLICY IF EXISTS "Allow public update" ON upcoming_orders;
    DROP POLICY IF EXISTS "Allow public update" ON vendors;
    DROP POLICY IF EXISTS "Allow public update" ON menu_items;
    DROP POLICY IF EXISTS "Allow public update" ON box_types;
    DROP POLICY IF EXISTS "Allow public update" ON box_quotas;
    DROP POLICY IF EXISTS "Allow public update" ON item_categories;
    DROP POLICY IF EXISTS "Allow public update" ON client_statuses;
    DROP POLICY IF EXISTS "Allow public update" ON navigators;
    DROP POLICY IF EXISTS "Allow public update" ON nutritionists;
    DROP POLICY IF EXISTS "Allow public update" ON admins;
    DROP POLICY IF EXISTS "Allow public update" ON app_settings;
    DROP POLICY IF EXISTS "Allow public update" ON form_submissions;
    DROP POLICY IF EXISTS "Allow public update" ON signatures;
    DROP POLICY IF EXISTS "Allow public update" ON billing_records;
    DROP POLICY IF EXISTS "Allow public update" ON delivery_history;
    DROP POLICY IF EXISTS "Allow public update" ON order_vendor_selections;
    DROP POLICY IF EXISTS "Allow public update" ON order_items;
    DROP POLICY IF EXISTS "Allow public update" ON order_box_selections;
    DROP POLICY IF EXISTS "Allow public update" ON upcoming_order_vendor_selections;
    DROP POLICY IF EXISTS "Allow public update" ON upcoming_order_items;
    DROP POLICY IF EXISTS "Allow public update" ON upcoming_order_box_selections;
    DROP POLICY IF EXISTS "Allow public update" ON stops;
    DROP POLICY IF EXISTS "Allow public update" ON drivers;
    DROP POLICY IF EXISTS "Allow public update" ON routes;
    DROP POLICY IF EXISTS "Allow public update" ON equipment;
    DROP POLICY IF EXISTS "Allow public update" ON forms;
    DROP POLICY IF EXISTS "Allow public update" ON questions;
    DROP POLICY IF EXISTS "Allow public update" ON filled_forms;
    DROP POLICY IF EXISTS "Allow public update" ON form_answers;
    DROP POLICY IF EXISTS "Allow public update" ON order_history;
    DROP POLICY IF EXISTS "Allow public update" ON navigator_logs;
    DROP POLICY IF EXISTS "Allow public update" ON schedules;
    DROP POLICY IF EXISTS "Allow public update" ON settings;
    DROP POLICY IF EXISTS "Allow public update" ON city_colors;
    DROP POLICY IF EXISTS "Allow public update" ON passwordless_codes;
    DROP POLICY IF EXISTS "Allow public update" ON route_runs;
EXCEPTION
    WHEN undefined_object THEN NULL;
END $$;

-- Create permissive policies for UPDATE
CREATE POLICY "Allow public update" ON clients FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON orders FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON upcoming_orders FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON vendors FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON menu_items FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON box_types FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON box_quotas FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON item_categories FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON client_statuses FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON navigators FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON nutritionists FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON admins FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON app_settings FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON form_submissions FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON signatures FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON billing_records FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON delivery_history FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON order_vendor_selections FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON order_items FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON order_box_selections FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON upcoming_order_vendor_selections FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON upcoming_order_items FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON upcoming_order_box_selections FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON stops FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON drivers FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON routes FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON equipment FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON forms FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON questions FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON filled_forms FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON form_answers FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON order_history FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON navigator_logs FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON schedules FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON settings FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON city_colors FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON passwordless_codes FOR UPDATE USING (true);
CREATE POLICY "Allow public update" ON route_runs FOR UPDATE USING (true);

-- Drop existing DELETE policies
DO $$
BEGIN
    DROP POLICY IF EXISTS "Allow public delete" ON clients;
    DROP POLICY IF EXISTS "Allow public delete" ON orders;
    DROP POLICY IF EXISTS "Allow public delete" ON upcoming_orders;
    DROP POLICY IF EXISTS "Allow public delete" ON vendors;
    DROP POLICY IF EXISTS "Allow public delete" ON menu_items;
    DROP POLICY IF EXISTS "Allow public delete" ON box_types;
    DROP POLICY IF EXISTS "Allow public delete" ON box_quotas;
    DROP POLICY IF EXISTS "Allow public delete" ON item_categories;
    DROP POLICY IF EXISTS "Allow public delete" ON client_statuses;
    DROP POLICY IF EXISTS "Allow public delete" ON navigators;
    DROP POLICY IF EXISTS "Allow public delete" ON nutritionists;
    DROP POLICY IF EXISTS "Allow public delete" ON admins;
    DROP POLICY IF EXISTS "Allow public delete" ON app_settings;
    DROP POLICY IF EXISTS "Allow public delete" ON form_submissions;
    DROP POLICY IF EXISTS "Allow public delete" ON signatures;
    DROP POLICY IF EXISTS "Allow public delete" ON billing_records;
    DROP POLICY IF EXISTS "Allow public delete" ON delivery_history;
    DROP POLICY IF EXISTS "Allow public delete" ON order_vendor_selections;
    DROP POLICY IF EXISTS "Allow public delete" ON order_items;
    DROP POLICY IF EXISTS "Allow public delete" ON order_box_selections;
    DROP POLICY IF EXISTS "Allow public delete" ON upcoming_order_vendor_selections;
    DROP POLICY IF EXISTS "Allow public delete" ON upcoming_order_items;
    DROP POLICY IF EXISTS "Allow public delete" ON upcoming_order_box_selections;
    DROP POLICY IF EXISTS "Allow public delete" ON stops;
    DROP POLICY IF EXISTS "Allow public delete" ON drivers;
    DROP POLICY IF EXISTS "Allow public delete" ON routes;
    DROP POLICY IF EXISTS "Allow public delete" ON equipment;
    DROP POLICY IF EXISTS "Allow public delete" ON forms;
    DROP POLICY IF EXISTS "Allow public delete" ON questions;
    DROP POLICY IF EXISTS "Allow public delete" ON filled_forms;
    DROP POLICY IF EXISTS "Allow public delete" ON form_answers;
    DROP POLICY IF EXISTS "Allow public delete" ON order_history;
    DROP POLICY IF EXISTS "Allow public delete" ON navigator_logs;
    DROP POLICY IF EXISTS "Allow public delete" ON schedules;
    DROP POLICY IF EXISTS "Allow public delete" ON settings;
    DROP POLICY IF EXISTS "Allow public delete" ON city_colors;
    DROP POLICY IF EXISTS "Allow public delete" ON passwordless_codes;
    DROP POLICY IF EXISTS "Allow public delete" ON route_runs;
EXCEPTION
    WHEN undefined_object THEN NULL;
END $$;

-- Create permissive policies for DELETE
CREATE POLICY "Allow public delete" ON clients FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON orders FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON upcoming_orders FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON vendors FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON menu_items FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON box_types FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON box_quotas FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON item_categories FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON client_statuses FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON navigators FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON nutritionists FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON admins FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON app_settings FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON form_submissions FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON signatures FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON billing_records FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON delivery_history FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON order_vendor_selections FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON order_items FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON order_box_selections FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON upcoming_order_vendor_selections FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON upcoming_order_items FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON upcoming_order_box_selections FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON stops FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON drivers FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON routes FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON equipment FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON forms FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON questions FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON filled_forms FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON form_answers FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON order_history FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON navigator_logs FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON schedules FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON settings FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON city_colors FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON passwordless_codes FOR DELETE USING (true);
CREATE POLICY "Allow public delete" ON route_runs FOR DELETE USING (true);
